<a href="https://colab.research.google.com/github/carloscifuentesingsoft1560-cyber/Learning_Pytorch/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cpu


In [5]:
escalar = torch.randn(1)
vector = torch.zeros(1,10)
matriz = torch.ones(2,2)



tensor([[1., 1.],
        [1., 1.]])

In [6]:
t5 = torch.randn(5,2,3)
t5

tensor([[[-0.1450,  0.1640,  1.4430],
         [-0.5637,  1.2327, -2.2214]],

        [[-0.5442, -1.9878,  0.5801],
         [ 0.2871, -0.2466, -1.5872]],

        [[-0.5212, -1.7291,  0.0974],
         [ 1.2265,  0.5224, -1.2463]],

        [[ 0.5263, -1.9973, -0.4087],
         [ 1.2383, -1.2308, -2.3108]],

        [[-0.8253,  0.1016, -1.1636],
         [-0.3792, -0.0302,  1.4073]]])

In [11]:
torch.tensor([[2,2], [3,3]])

tensor([[2, 2],
        [3, 3]])