<a href="https://colab.research.google.com/github/carloscifuentesingsoft1560-cyber/Learning_Pytorch/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cu128


In [3]:
escalar = torch.randn(1)
vector = torch.zeros(1,10)
matriz = torch.ones(2,2)



In [4]:
t5 = torch.randn(5,2,3)
t5

tensor([[[-1.4448, -0.2171,  0.3704],
         [-0.9563,  0.9253,  1.4512]],

        [[ 0.0829, -1.2147, -0.4951],
         [ 1.5474,  0.5091,  1.1770]],

        [[ 0.1951,  0.4587, -0.8363],
         [-1.7158,  1.0971,  0.7453]],

        [[-0.6052, -0.1404, -0.5673],
         [ 1.7533, -0.1348, -1.5580]],

        [[-0.0094,  0.4303, -0.4838],
         [ 0.2524,  0.5962,  1.2431]]])

In [5]:
torch.tensor([[2,2], [3,3]])

tensor([[2, 2],
        [3, 3]])

In [6]:
print(f"La shape de la matriz es {matriz.shape}")
print(f"La shpe de t5 es {t5.shape}")

La shape de la matriz es torch.Size([2, 2])
La shpe de t5 es torch.Size([5, 2, 3])


In [7]:
print(f"La shape de la matriz es {matriz.ndim}")
print(f"La shpe de t5 es {t5.ndim}")

La shape de la matriz es 2
La shpe de t5 es 3


In [8]:
print(f"El tensor de la matriz tiene elementos de tipo {matriz.dtype}")
# print(f"La shpe de t5 es {t5.ndim}")

El tensor de la matriz tiene elementos de tipo torch.float32


In [9]:
matriz_float32 = torch.tensor([[3.1,3.2],[3.3,3.4]])
matriz_unit64 = torch.tensor([[3,3],[3,3]])

# matriz_float32.dtype, matriz_unit64.dtype

(matriz_float32 + matriz_unit64).dtype

torch.float32

In [10]:
matriz_unit64.to(torch.float32)

tensor([[3., 3.],
        [3., 3.]])

In [11]:
matriz_unit64.device

device(type='cpu')

In [12]:
torch.cuda.is_available()

True

In [14]:
if torch.cuda.is_available():
  matriz_unit64_cuda = matriz_unit64.to(torch.device("cuda"))

  print(matriz_unit64_cuda,matriz_unit64_cuda.type())
  print(matriz_unit64_cuda.to("cpu", torch.float32))


  matriz_unit64_cuda + matriz_unit64

tensor([[3, 3],
        [3, 3]], device='cuda:0') torch.cuda.LongTensor
tensor([[3., 3.],
        [3., 3.]])


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!