<a href="https://colab.research.google.com/github/carloscifuentesingsoft1560-cyber/Learning_Pytorch/blob/main/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.11.0+cu128


In [3]:
escalar = torch.randn(1)
vector = torch.zeros(1,10)
matriz = torch.ones(2,2)



In [4]:
t5 = torch.randn(5,2,3)
t5

tensor([[[ 1.0401, -0.4379,  1.0330],
         [ 0.6025,  0.9318, -0.4641]],

        [[ 2.0228,  1.5362,  0.9619],
         [ 0.6402, -0.6865,  0.4373]],

        [[ 0.9186,  0.7732,  0.0245],
         [ 0.3763,  0.2445,  0.1211]],

        [[-0.7273, -0.6931,  0.3425],
         [ 0.3569, -0.3567,  0.8564]],

        [[ 1.3213,  0.1222,  0.8868],
         [-0.3075,  0.8751, -0.4283]]])

In [5]:
torch.tensor([[2,2], [3,3]])

tensor([[2, 2],
        [3, 3]])

In [6]:
print(f"La shape de la matriz es {matriz.shape}")
print(f"La shpe de t5 es {t5.shape}")

La shape de la matriz es torch.Size([2, 2])
La shpe de t5 es torch.Size([5, 2, 3])


In [7]:
print(f"La shape de la matriz es {matriz.ndim}")
print(f"La shpe de t5 es {t5.ndim}")

La shape de la matriz es 2
La shpe de t5 es 3


In [8]:
print(f"El tensor de la matriz tiene elementos de tipo {matriz.dtype}")
# print(f"La shpe de t5 es {t5.ndim}")

El tensor de la matriz tiene elementos de tipo torch.float32


In [9]:
matriz_float32 = torch.tensor([[3.1,3.2],[3.3,3.4]])
matriz_unit64 = torch.tensor([[3,3],[3,3]])

# matriz_float32.dtype, matriz_unit64.dtype

(matriz_float32 + matriz_unit64).dtype

torch.float32

In [10]:
matriz_unit64.to(torch.float32)

tensor([[3., 3.],
        [3., 3.]])

In [11]:
matriz_unit64.device

device(type='cpu')

In [12]:
torch.cuda.is_available()

True

In [14]:
if torch.cuda.is_available():
  matriz_unit64_cuda = matriz_unit64.to(torch.device("cuda"))

  print(matriz_unit64_cuda,matriz_unit64_cuda.type())
  print(matriz_unit64_cuda.to("cpu", torch.float32))




tensor([[3, 3],
        [3, 3]], device='cuda:0') torch.cuda.LongTensor
tensor([[3., 3.],
        [3., 3.]])


In [16]:
type(matriz.numpy())

numpy.ndarray

In [17]:
import numpy as np

In [19]:
vector = np.ones(5)
torch.from_numpy(vector).dtype

torch.float64

In [20]:
zeros_tensor = torch.zeros((3,4))

ones_tensor = torch.ones((3,4))

random_tensror = torch.randn((4))

In [28]:
random_tensror

tensor([ 1.1588, -0.0105,  0.1093,  1.8940])

In [30]:
added_tensor = zeros_tensor + ones_tensor

subtracted_tensor = zeros_tensor - ones_tensor

multipied_tensor = zeros_tensor * ones_tensor

divided_tensor = random_tensror / ones_tensor

In [32]:
divided_tensor

tensor([[ 1.1588, -0.0105,  0.1093,  1.8940],
        [ 1.1588, -0.0105,  0.1093,  1.8940],
        [ 1.1588, -0.0105,  0.1093,  1.8940]])

In [37]:
matrix1 = torch.randn(2,3)
matrix2 = torch.randn(3,2)

# print (f"matriz1 shape: {matrix1.shape}")
# print (f"matriz2 shape: {matrix2.shape}")


torch.matmul(matrix1, matrix2).shape

torch.Size([2, 2])